export const FETCH_GIPHIES_START = 'FETCH_GIPHIES_START';
export const FETCH_GIPHIES_SUCCESS = 'FETCH_GIPHIES_SUCCESS';
export const FETCH_GIPHIES_ERROR = 'FETCH_GIPHIES_ERROR';
export const UPDATE_GIPHY = 'UPDATE_GIPHY';
export const SORT_GIPHIES = 'SORT_GIPHIES';
