version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.9.0

    deploy:
      steps:
        - checkout
        - run:
            name: Deploy Master to Heroku
            command: |
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

      filters:
        branches:
          only: master

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run: npm install
      - run: npm run webdriver-update
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run: npm run lint
      - run: npm test
      - run:
          command: npm start
          background: true

      - run: npm run e2e
