version: 2
jobs:
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

  build:
    docker:
      - image: cypress/base:8

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run: npm run lint
      - run: npm test
      - run:
          command: NODE_ENV=production npm start & npm run wait-on
          background: true

      - run: npm run e2e
